name: Gitleaks Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manuel tetikleme için

jobs:
  gitleaks:
    name: Run Gitleaks Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: 🔒 Run Gitleaks Scan
        uses:  gitleaks/gitleaks-action@v2.3.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token
          scan: true  # Taramayı aktif et
          report_format: "json"  # Rapor formatını json olarak al
          report_path: "gitleaks_reports/report.json"  # Rapor dosyasının yolu
